%YAML:1.0
video_type: 2
filter: 6
window_size: 15
bb_path:  bb.txt
video_path: /home/hugo/Documents/Mestrado/alov300
init_path: /home/hugo/Documents/Mestrado/codigoRastreador/parametros/01_david_init.txt
gt_path: /home/hugo/Documents/Mestrado/codigoRastreador/parametros/01_david_gt.txt
detect: 1
track: 1
detect_failure: 1
show: 1
repeat_video: 0
print_status: 1
valid: 0
conf: 0

